version: '3.5'

services:

  server:
    image: robot:server
    build:
      context: ./server
    volumes:
      - .:/server
    expose:
      - 4001
    ports:
      - 4001:4001

  client:
    image: robot:client
    build:
      context: ./client
    # volumes:
    #   - ./client:/var/www/
    ports:
      - 8080:80

  redis:
    image: redis:3.2
    expose:
      - 6379
    ports:
      - 6379:6379

# volumes:
#   app-data:
#     external: false